# Generated by Django 4.1.3 on 2022-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_drop_off_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='serviceCategory_new',
            field=models.CharField(blank=True, choices=[('RoomClearing', 'RoomClearing'), ('WalkingDog', 'WalkingDog'), ('GardenClearing', 'GardenClearing'), ('CarWash', 'CarWash')], default='RoomClearing', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='servicePrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True),
        ),
    ]
