# Generated by Django 4.1.3 on 2022-12-01 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_job_time_alter_trip_driver_alter_trip_rider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='job_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 6, 39, 45, 65863)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pick_up_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='housekeeper_address'),
        ),
    ]
