# Generated by Django 4.1.3 on 2022-12-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_trip_job_time_alter_trip_pick_up_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='job_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 7, 38, 31, 864785)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pick_up_address',
            field=models.CharField(default='fake', max_length=255, verbose_name='housekeeper_address'),
        ),
    ]
