# Generated by Django 4.1.3 on 2022-12-01 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_trip_job_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='job_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 7, 59, 36, 593104)),
        ),
    ]
