# Generated by Django 4.1.3 on 2022-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_trip_job_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='job_time',
            field=models.DateTimeField(default='Dec. 1, 2022, 7:51 a.m.'),
        ),
    ]
