# Generated by Django 4.1.3 on 2022-12-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_job_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='job_time',
        ),
    ]
